name: build with EMCC

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Emscripten toolchain
      # You may pin to the exact commit or the version.
      # uses: mymindstorm/setup-emsdk@2a4a91b6145fc9f6520782044bd2595ec02c323e
      uses: mymindstorm/setup-emsdk@v6
    - name: build
      run: make node
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.1.4
      with:
        # Artifact name
        name: executable files
        # A file, directory or wildcard pattern that describes what to upload
        path: |
          Pmachine.js
          Pmachine.wasm
